language: java

install: true

script:
- gradle clean
- gradle build 
- gradle assemble
- gradle check

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop